### ISSUE TITLE
Exception - java.lang.NumberFormatException: For input string: "8999999999999999999"

### ISSUE THREAD

**Issue by ITMentalist** [IBM/nagios-for-i#22]
Hi ,

We have a check that we need to do for Journal Sequence Numbers to which can go to a large value. (e.g. 9999999999999999999), 

if we add the check here to that value : 

![image](https://user-images.githubusercontent.com/5381496/150973217-5add2ae2-a4a6-4ffd-bde2-91a1b1be8f43.png)

This error shows during check: 

![image](https://user-images.githubusercontent.com/5381496/150973282-b448ef12-9cf6-42c3-8f2e-1b2d7c33df0b.png)

It looks like its the plugin that cannot handle the large value but we are not able to find where this large value resides, any help will be appreciated to see where we need to increase this value to accomplish the check. 

Thanks

**Comment by williamlea1** [comment]
Hi, 

thats a custom sql so do you have the statement you are running? Also my understanding is the journal seq number is limited to 9,999,999,999. So all those 9's seem to many?

Cheers

**Comment by ITMentalist** [comment]
Hi William, 

Yes it is a custom SQL we are running (cant unfortunately share the code), but it does return an 15 Long integer that shows the current Journal Sequence. 

It seems our system's journal sequence can go longer than the one you have as we are on MAXOPT2.

**Comment by fcuerno001** [comment]
Hi William, could you give us an idea how is the query? wooow been a excellet help if we have idea how to configure that!!!!

**Comment by williamlea1** [comment]
Hi ITMentalist

> It seems our system's journal sequence can go longer than the one you have as we are on MAXOPT2.

Maxopt2 is still 999,999,999,999 its Opt3 that has some silly figure and that starts with 18,xxx,xxx,xxx,xxx,xxx,xxx isnt it ?

Cheers Will

**Comment by williamlea1** [comment]
> Hi William, could you give us an idea how is the query? wooow been a excellet help if we have idea how to configure that!!!!

Hi fcuerno001,
I would look at qsys2.display_journal table, might be able to get what info you need from that?

Cheers Will.

**Comment by fcuerno001** [comment]
Hi Williamlea1, 

Thank you so much, i will check table qsys2.display_journal thank for information.

**Comment by ITMentalist** [comment]
found a workaround to rather cast the values of a percentage to 2 digits than the big numbers.
