### ISSUE TITLE
CPU Utilization and Disk Nagios not able to get showing 0.00% CPU with IBM i 7.3

### ISSUE THREAD

**Issue by anik4good** [IBM/nagios-for-i#41]
Hi Team,

Recently we have implemented the as400 plugin for Nagiosxi from the below link
https://github.com/IBM/nagios-for-i/tree/master

However the CPU utilization is showing 0.0%, I have tried to run the check command manually from the terminal it's showing 0.0% coming from the AS400, 
https://paste.pics/QO9YL

also, 1 disk Nagios won't be able to detect it detect 2 Disk from our as400
https://paste.pics/QO9YR

it won't detect the IASP2 Disk but Detecting Other two

I am seeking your advice on this matter, please let me know about this one how we can solve it

**Comment by afholman** [comment]
Hello, I looked into why the CPU utilization was returning 0% for you. It isn't a problem with your system at all. According to this [page](https://www.ibm.com/docs/en/i/7.3?topic=services-system-status-info-view), the AVERAGE_CPU_UTILIZATION in the SYSTEM_STATUS_INFO view will always return 0%. Now we should be using the [SYSTEM_STATUS_INFO table function](https://www.ibm.com/docs/en/i/7.3?topic=services-system-activity-info-table-function). I created a PR, which is listed above, that should fix that problem.

I'm not sure why it isn't detecting the IASP2 disk on your system though. Regardless, it definitely seems like that'd a be separate issue. If you're still experiencing that problem, would you mind creating a new issue to track that problem with any more details you have about it?

**Comment by afholman** [comment]
Closing out the issue now that the PR has been merged into master. If you use the most recent packages, it should display the correct CPU utilization percentage. Please do create a separate issue if the second problem you mentioned is still occurring.
