### ISSUE TITLE
Unable to import Nagios XI config wizards

### ISSUE THREAD

**Issue by rohithsharma84** [IBM/nagios-for-i#44]
I'm using Nagios XI ver 2024R1.2.1 and when I tried to import ibmiservice.zip or ibmicustomsql.zip I get the message "Wizard installation failed. Uploaded zip file is not a config wizard."

I see these files are from 2019, are these the latest builds available?

**Comment by williamlea1** [comment]
Hi, Thats when it was written. No new ones are available. Seems IBM has pulled away from this for the minute. 

Try downloading them from GITHUB and try again?

**Comment by afholman** [comment]
I merged in some new changes and rebuilt the zip files to include the updates. It sounds like those are working for you now, so I'll close out this issue. If you do run into any issues with them feel free to open a new issue or reopen this one.
