### ISSUE TITLE
java.io.EOFException Insert Host Failed. 

### ISSUE THREAD

**Issue by ITMentalist** [IBM/nagios-for-i#8]
Hi 

We are receiving the following error: 
![image](https://user-images.githubusercontent.com/5381496/89615025-f1f77d80-d885-11ea-9b33-a82b7375fc11.png)
when trying to add out host. 

Can you please advise where to look for the error logs to determine the root cause of this issue? 

Many thanks

Marius

**Comment by zhangyan101** [comment]
This problem is caused by the file /usr/local/nagios/var/Nagios.host.java.config.ser is broken. Remove the file can fix this problem.

**Comment by ITMentalist** [comment]
thank you , that worked 100%
